-- local M = {}

-- local config = {
--     display_table = require("cheatsheet.config.display_table").default
-- }
-- function M.merge_user_opts(user_opts)
--     config = vim.tbl_deep_extend("force", config, user_opts)
-- end
--
-- return setmetatable(M, {
--     _index = function(_, k)
--         return config[k]
--     end,
-- })
